# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
