# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='time',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='venue',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
