# Generated by Django 2.2.9 on 2020-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
